#define HAA_SETUP_MODE_SYSPARAM "setup"
#define CUSTOM_REPO_SYSPARAM    "ota_server"
#define AUTO_OTA_SYSPARAM       "aota"
#define OTA_VERSION_SYSPARAM    "ota_repo"
#define USER_VERSION_SYSPARAM   "ota_version"
#define ESPY_JSON_SYSPARAM      "conf"
